projects:
  app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:8800
  database:
    schemaPath: src/generated/prisma.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: database/prisma.yml
